import { SearchForm } from "@/components/search-form";
import { ArrowRight, Bell, Brain, CheckCircle2, Globe2, ShieldCheck, Star } from "lucide-react";

const destinations = ["Istanbul", "Dubai", "Antalya", "Paris", "Rome", "Tbilisi"];
const faqs = ["How are package scores calculated?", "Are prices live?", "Can I save and share trips?", "Which APIs can be connected later?"];

export default function HomePage() {
  return <main>
    <section className="premium-gradient px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-3xl"><span className="rounded-full bg-white px-4 py-2 text-sm font-bold text-ocean shadow">AI-powered full trip comparison</span><h1 className="mt-6 text-5xl font-black tracking-tight text-navy md:text-7xl">Compare the whole trip, not only the ticket.</h1><p className="mt-6 text-xl text-slate-600">TravelExpert AI combines flights, hotels, transfers, insurance, visa notes, local costs, and AI advice into premium package recommendations for Azerbaijan and nearby markets.</p></div><div className="mt-10"><SearchForm /></div><div className="mt-8 grid gap-4 md:grid-cols-3">{["Mock APIs today, real providers tomorrow", "Transparent full-cost calculator", "AI scoring with hidden-cost warnings"].map((item)=><div key={item} className="flex items-center gap-3 rounded-2xl bg-white/80 p-4 font-semibold text-navy"><CheckCircle2 className="text-emerald-500"/>{item}</div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-3"><div className="lg:col-span-1"><h2 className="text-3xl font-black text-navy">Popular destinations</h2><p className="mt-3 text-slate-600">SEO-ready destination cards designed for package landing pages.</p></div><div className="grid gap-4 md:grid-cols-3 lg:col-span-2">{destinations.map((d)=><div key={d} className="rounded-[2rem] border border-slate-200 p-6 shadow-sm"><Globe2 className="text-ocean"/><h3 className="mt-5 text-xl font-bold">{d}</h3><p className="mt-2 text-sm text-slate-500">Flights + hotel + transfer package estimates.</p></div>)}</div></div></section>
    <section className="bg-skysoft/60 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-3">{[{icon:Brain,title:"AI chooses the best package",text:"Ranks cheapest, best value, fastest, family, and premium combinations using weighted travel scoring."},{icon:ShieldCheck,title:"Trust and transparency",text:"Every mock estimate is labeled, with warnings for baggage, refund rules, visa assumptions, and hidden provider fees."},{icon:Bell,title:"Price alert growth loop",text:"Users can save searches, set alerts, and upgrade for advanced tracking and PDF itinerary exports."}].map(({icon:Icon,title,text})=><div key={title} className="rounded-[2rem] bg-white p-8 shadow-premium"><Icon className="text-ocean" size={34}/><h3 className="mt-5 text-2xl font-bold text-navy">{title}</h3><p className="mt-3 text-slate-600">{text}</p></div>)}</div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-black text-navy">Featured package examples</h2><div className="mt-6 space-y-4">{["Baku to Istanbul family week", "Baku to Dubai business escape", "Student weekend in Tbilisi"].map((p)=><div key={p} className="flex items-center justify-between rounded-2xl border p-5"><span className="font-bold">{p}</span><ArrowRight className="text-ocean"/></div>)}</div></div><div><h2 className="text-3xl font-black text-navy">Testimonials</h2>{["Finally I can see the real total before booking.", "The family package notes are more useful than a normal flight search."].map(t=><blockquote key={t} className="mt-6 rounded-[2rem] bg-white p-6 shadow-premium"><Star className="text-gold"/><p className="mt-3 text-lg font-semibold">“{t}”</p></blockquote>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8"><h2 className="text-3xl font-black text-navy">FAQ</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{faqs.map(f=><div key={f} className="rounded-2xl border border-slate-200 p-5 font-semibold">{f}</div>)}</div><div className="mt-10 rounded-[2rem] bg-navy p-8 text-white"><h2 className="text-3xl font-black">Ready to compare your complete trip?</h2><p className="mt-3 text-white/70">Start with mock data today and connect provider APIs as partnerships go live.</p></div></section>
  </main>;
}
